version: "3"
services:
  postgres:
    container_name: postgres
    image:   postgres:16-alpine
    environment:
      - POSTGRES_USER=artikum
      - POSTGRES_PASSWORD=12345qwerty
    volumes:
      - pg-volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  backend:
    container_name: backend
    image: backend:1.0
    depends_on:
      - postgres
    ports:
      - "3100:3000"
  
  frontend:
    container_name: frontend
    image: frontend:1.0
    ports:
      - "3000:3000"
    depends_on:
      - backend
  

volumes:
  pg-volume:
    external: true
    name: pg-volume